# Generated by Django 4.0.3 on 2022-03-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=17)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('vin_number', models.CharField(default=None, max_length=20)),
                ('available', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=17)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('current_location', models.CharField(max_length=50)),
                ('daily_rate', models.CharField(max_length=20)),
                ('available', models.CharField(max_length=20)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=17)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.customer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.equipment')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.renter')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.driver')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.equipment')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_reserve.renter')),
            ],
        ),
    ]
